import type { Metadata } from "next";
import { Josefin_Sans, Indie_Flower } from "next/font/google";
import "./globals.css";

import { Navbar } from "./component/Navbar";
import { ToastProps } from "./provider/ToastProps";
import { getCurrentUser } from "./action/getCurrentUser";
import { RegisterModal } from "./component/modal/RegisterModal";
import { LoginModal } from "./component/modal/LoginModal";
import { ClientOnly } from "./component/ClientOnly";
import { AddnewModal } from "./component/modal/AddnewModal";


const fontBody = Josefin_Sans({
  variable: "--font-josefin",
  subsets: ["latin"],
});

const fontTitle= Indie_Flower({
  variable: "--font-indie",
  subsets: ["latin"],
  weight:["400"]
});

export const metadata: Metadata = {
  title: "Create BucketList App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const curUser = await getCurrentUser()
  return (
    <html lang="en">
      <body
        className={`${fontBody.variable} ${fontTitle.variable} antialiased`}
      >
        <ClientOnly>
            <ToastProps />
            <RegisterModal />
            <LoginModal />
            <AddnewModal />
            <Navbar curUser = {curUser}/> 
            <div className="fixed z-0 top-0 left-0 w-full h-[50vh] bg-gradient-to-b from-orange-500/50 via-blue-700/75 to-blue-100/5 "></div>
            {children}
        </ClientOnly>
      </body>
    </html>
  );
}
